preload = ~/Pictures/wallpapers/alto/pink_night_temple.png
preload = ~/Pictures/wallpapers/vending_machine.jpg

# Use the actual monitor names from hyprctl monitors
wallpaper = eDP-1,~/Pictures/wallpapers/alto/pink_night_temple.png
wallpaper = DP-1,~/Pictures/wallpapers/vending_machine.jpg

# Or use this to apply to all monitors:
# wallpaper = ,~/Pictures/wallpapers/dune.png

splash = false
ipc = on
