# NOTE: Switched to swww instead of hyprpaper
preload = ~/Pictures/wallpapers/alto/pink_night_temple.png
preload = ~/Pictures/wallpapers/vending_machine.jpg
preload = ~/Pictures/wallpapers/dune/wallhaven-k883md.jpg
preload = ~/Pictures/wallpapers/dune/wallhaven-ml3jm8.jpg

# Use the actual monitor names from hyprctl monitors
wallpaper = eDP-1,~/Pictures/wallpapers/dune/wallhaven-k883md.jpg
wallpaper = DP-1,~/Pictures/wallpapers/dune/wallhaven-ml3jm8.jpg

# Or use this to apply to all monitors:
# wallpaper = ,~/Pictures/wallpapers/dune.png

splash = false
ipc = on
